country_names = [
    "Qatar",
    "Germany",
    "Denmark",
    "Brazil",
    "France",
    "Belgium",
    "Croatia",
    "Spain",
    "Serbia",
    "England",
    "Switzerland",
    "Netherlands",
    "Argentina",
    "Iran",
    "South Korea",
    "Japan",
    "Saudi Arabia",
    "Ecuador",
    "Uruguay",
    "Canada",
    "Ghana",
    "Senegal",
    "Portugal",
    "Poland",
    "Tunisia",
    "Morocco",
    "Cameroon",
    "USA",
    "Mexico",
]
